import { computed, toValue, type MaybeRefOrGetter } from 'vue'
import { useI18n } from 'vue-i18n'
import contentData from '@/generated/content.json'
import type { ContentEntry, Locale, Slug } from '@/lib/frontmatter'

export type { ContentEntry } from '@/lib/frontmatter'

// Two jobs in one:
//  1. Keep content images in the client bundle — compiled content HTML
//     references them, so the build must emit the files.
//  2. Runtime asset resolution: compiled HTML contains `__QPD_ASSET__:<name>`
//     tokens (see Pic.vue), because the correct URL differs per build —
//     `/src/assets/…` under `vite dev`, hashed `/assets/…-HASH.png` in
//     production/SSR.  This map resolves tokens to whichever is right for the
//     build that is running.
const assetUrls = import.meta.glob('../assets/*', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

const assetByName: Record<string, string> = Object.fromEntries(
  Object.entries(assetUrls).map(([p, url]) => [p.split('/').pop()!, url]),
)

const ASSET_TOKEN_RE = /__QPD_ASSET__:([^"]+)/g

// Replace `__QPD_ASSET__:<basename>` tokens in compiled HTML with the URL Vite
// assigned the asset in *this* build (dev server path or hashed prod path).
export function resolveAssetUrls(html: string): string {
  ASSET_TOKEN_RE.lastIndex = 0
  return html.replace(ASSET_TOKEN_RE, (token, name: string) => assetByName[name] ?? token)
}

// Content entry system.  Entries are precompiled at build time into
// `src/generated/content.json` (see scripts/compile-content.mjs): frontmatter,
// markdown→HTML (markdown-it + MDC + Shiki + KaTeX), and reference metadata
// are all baked in.  This module is a pure runtime consumer of that file — the
// client never runs markdown-it/Shiki/KaTeX or the MDC content components.

type ContentData = Record<Locale, Record<Slug, ContentEntry>>

// Generated by scripts/compile-content.mjs, so the shape is known by
// construction — cast the JSON import through the narrow `ContentEntry` type.
const entries = contentData as ContentData

// Resolve a slug for a locale, falling back: exact locale -> language prefix
// (e.g. "zh-CN" -> "zh") -> English.
export function getEntry(slug: Slug, locale: Locale): ContentEntry | undefined {
  const prefix = locale.split('-')[0]!
  return entries[locale]?.[slug] ?? entries[prefix]?.[slug] ?? entries.en?.[slug]
}

// All slugs (union across locales), for validation/navigation.
export function listSlugs(): string[] {
  const set = new Set<string>()
  for (const byLocale of Object.values(entries)) {
    for (const slug of Object.keys(byLocale)) set.add(slug)
  }
  return [...set]
}

// Reactive entry lookup following the active i18n locale.  `slug` may be a
// ref/getter: the same component instance is reused when the router navigates
// between two `/blog/:slug` routes (only the prop updates, setup does not
// re-run), so the value must be re-read inside the computed.
export function useEntry(slug: MaybeRefOrGetter<Slug>) {
  const { locale } = useI18n()
  return computed(() => getEntry(toValue(slug), locale.value))
}

// All entries resolved for a locale (falling back per-slug), newest first.
export function listEntries(locale: Locale): ContentEntry[] {
  return listSlugs()
    .map((slug) => getEntry(slug, locale))
    .filter((e): e is ContentEntry => e !== undefined)
    .sort((a, b) => (b.date || '').localeCompare(a.date || ''))
}

export function useEntries() {
  const { locale } = useI18n()
  return computed(() => listEntries(locale.value))
}

// Blog entries (in the active locale) that reference a given problem via a
// `:problem-card{id=…}` component.  Reactive to locale changes.  The reference
// set is precomputed in content.json — no markdown parsing at runtime.
export function useEntriesReferencingProblem(id: MaybeRefOrGetter<string>) {
  const { locale } = useI18n()
  return computed(() =>
    listEntries(locale.value).filter((e) => e.problemIds.includes(toValue(id))),
  )
}

// Blog entries (in the active locale) that reference a given blog entry via a
// `:blog-entry-card{slug=…}` component.  Reactive to locale changes.
export function useEntriesReferencingEntry(slug: MaybeRefOrGetter<string>) {
  const { locale } = useI18n()
  return computed(() =>
    listEntries(locale.value).filter((e) => e.entrySlugs.includes(toValue(slug))),
  )
}

// True when `author` co-authored the entry.  An entry authored by "all setters"
// is attributed to every setter.
export function entryAuthoredBy(entry: ContentEntry, author: string): boolean {
  if (entry.author === 'all') return true
  return entry.author.includes(author)
}
