<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import commitData from '@/generated/commit.json'

const { t } = useI18n()

interface CommitInfo {
  hash?: string
  shortHash?: string
  date?: string
  dateShort?: string
  message?: string
  author?: string
  url?: string
}

// Generated by scripts/commit-info.mjs; empty when git metadata is unavailable.
const commit = commitData as CommitInfo

const GITHUB_REPO = 'https://github.com/QPerDay/qperday.github.io'
const GITHUB_USER = 'https://github.com/QPerDay'
const EMAIL = 'makabaka1880@outlook.com'
</script>

<template>
  <article class="dev">
    <header class="dev__head">
      <h1 class="dev__title">{{ t('dev.title') }}</h1>
      <p class="dev__description">{{ t('dev.description') }}</p>
    </header>

    <section class="dev__section">
      <h2 class="dev__section-title">{{ t('dev.about.title') }}</h2>
      <p class="dev__body">{{ t('dev.about.body') }}</p>
    </section>

    <section class="dev__section">
      <h2 class="dev__section-title">{{ t('dev.commit.title') }}</h2>
      <template v-if="commit.hash">
        <dl class="meta-table">
          <dt>{{ t('dev.commit.hash') }}</dt>
          <dd>
            <a :href="commit.url" target="_blank" rel="noopener">
              <code>{{ commit.hash }}</code>
            </a>
          </dd>
          <dt>{{ t('dev.commit.message') }}</dt>
          <dd>{{ commit.message }}</dd>
          <dt>{{ t('dev.commit.date') }}</dt>
          <dd>{{ commit.dateShort }}</dd>
          <dt>{{ t('dev.commit.author') }}</dt>
          <dd>{{ commit.author }}</dd>
        </dl>
        <p class="dev__body">
          <a :href="commit.url" target="_blank" rel="noopener">{{ t('dev.commit.view') }}</a>
        </p>
      </template>
      <p v-else class="dev__body">{{ t('dev.commit.unavailable') }}</p>
    </section>

    <section class="dev__section">
      <h2 class="dev__section-title">{{ t('dev.contact.title') }}</h2>
      <dl class="meta-table">
        <dt>{{ t('dev.contact.email') }}</dt>
        <dd><a :href="`mailto:${EMAIL}`">{{ EMAIL }}</a></dd>
        <dt>{{ t('dev.contact.github') }}</dt>
        <dd><a :href="GITHUB_USER" target="_blank" rel="noopener">@QPerDay</a></dd>
      </dl>
    </section>

    <section class="dev__section">
      <h2 class="dev__section-title">{{ t('dev.architecture.title') }}</h2>
      <dl class="arch">
        <dt>{{ t('dev.architecture.source.label') }}</dt>
        <dd>{{ t('dev.architecture.source.body') }}</dd>
        <dt>{{ t('dev.architecture.build.label') }}</dt>
        <dd>{{ t('dev.architecture.build.body') }}</dd>
        <dt>{{ t('dev.architecture.data.label') }}</dt>
        <dd>{{ t('dev.architecture.data.body') }}</dd>
      </dl>
    </section>

    <section class="dev__section">
      <h2 class="dev__section-title">{{ t('dev.extend.title') }}</h2>
      <p class="dev__body">{{ t('dev.extend.body') }}</p>
      <ul class="dev__links">
        <li>
          <a :href="`${GITHUB_REPO}/blob/main/ARCHITECTURE.md`" target="_blank" rel="noopener">
            {{ t('dev.extend.architecture') }}
          </a>
        </li>
        <li>
          <a :href="`${GITHUB_REPO}/blob/main/EXTENDING.md`" target="_blank" rel="noopener">
            {{ t('dev.extend.extending') }}
          </a>
        </li>
      </ul>
    </section>
  </article>
</template>

<style scoped>
.dev {
  /* Same centered prose column as the blog entry page. */
  max-width: 44rem;
  margin: 0 auto;
  padding: var(--s6) 0;
}

.dev__head {
  margin-bottom: var(--s6);
  padding-bottom: var(--s6);
  border-bottom: 1px solid var(--c-border);
}
.dev__title {
  font-size: 2.5rem;
  line-height: 1.15;
  letter-spacing: -0.01em;
  margin: 0 0 var(--s3);
}
.dev__description {
  font-size: 1.15rem;
  line-height: 1.55;
  color: var(--c-muted);
  margin: 0;
}

.dev__section {
  margin-bottom: var(--s6);
}
/* Uppercase micro-headings, matching the blog page's section labels. */
.dev__section-title {
  font-size: 0.8rem;
  font-weight: 600;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  color: var(--c-muted);
  margin: 0 0 var(--s3);
}
.dev__body {
  line-height: 1.7;
  color: var(--c-fg);
  margin: 0;
}
.dev__section .dev__body + .dev__body {
  margin-top: var(--s3);
}

/* Two-column key/value table (shared look with the problem page's metadata). */
.meta-table {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: var(--s1) var(--s4);
  margin: 0 0 var(--s3);
  padding: var(--s3);
  border: 1px solid var(--c-border);
  border-radius: var(--radius);
}
.meta-table dt {
  color: var(--c-muted);
  font-weight: 600;
}
.meta-table dd {
  margin: 0;
  overflow-wrap: anywhere;
}
.meta-table code {
  font-family: var(--font-mono);
  color: var(--c-accent);
}

/* Architecture: bold label line, muted body, stacked. */
.arch {
  margin: 0;
}
.arch dt {
  font-weight: 600;
}
.arch dd {
  margin: 0 0 var(--s4);
  line-height: 1.7;
  color: var(--c-muted);
}
.arch dd:last-child {
  margin-bottom: 0;
}

.dev__links {
  list-style: none;
  padding: 0;
  margin: var(--s2) 0 0;
  display: flex;
  flex-direction: column;
  gap: var(--s1);
}

/* Very narrow screens: let the key/value table stack so long keys/values
   (the full hash) never overflow. */
@media (max-width: 640px) {
  .meta-table {
    grid-template-columns: 1fr;
    gap: var(--s1);
  }
}
</style>
