<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import commitData from '@/generated/commit.json'

const { t } = useI18n()

interface CommitInfo {
  hash?: string
  shortHash?: string
  date?: string
  dateShort?: string
  message?: string
  author?: string
  url?: string
}

// Generated by scripts/commit-info.mjs; empty when git metadata is unavailable.
const commit = commitData as CommitInfo
</script>

<template>
  <a
    v-if="commit.hash"
    class="commit"
    :href="commit.url"
    target="_blank"
    rel="noopener"
    :title="`${commit.hash} · ${commit.dateShort ?? ''} · ${commit.author ?? ''}`"
  >
    <span class="commit__label">{{ t('badge.latestCommit') }}</span>
    <span class="commit__sep" aria-hidden="true">·</span>
    <code class="commit__hash">{{ commit.shortHash }}</code>
    <span class="commit__sep" aria-hidden="true">·</span>
    <span class="commit__msg">{{ commit.message }}</span>
  </a>
</template>

<style scoped>
/* A plain-text annotation, not a pill: the site's aesthetic is dense,
   content-first and minimal-chrome, so the commit reads as a muted footnote
   line with a mono hash link. */
.commit {
  display: inline-flex;
  align-items: baseline;
  gap: 0.5rem;
  max-width: 100%;
  font-size: 0.8rem;
  color: var(--c-muted);
  text-decoration: none;
}
.commit__label {
  color: var(--c-faint);
  white-space: nowrap;
}
.commit__sep {
  color: var(--c-faint);
}
.commit__hash {
  font-family: var(--font-mono);
  color: var(--c-accent);
  white-space: nowrap;
}
.commit:hover .commit__hash {
  text-decoration: underline;
}
.commit__msg {
  /* min-width: 0 lets the flex item shrink below its content width so the
     ellipsis engages when the badge is wider than the viewport. */
  min-width: 0;
  color: var(--c-muted);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
